root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o lama2"
  bin = "./lama2 --lsp"
  delay = 1000
  exclude_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css", "scss", "js", "ts", "sql", "jpeg", "jpg", "gif", "png", "bmp", "svg", "webp", "ico"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = true
  send_interrupt = false
  rerun = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true