site_name: Hexmos Lama2
site_url: http://hexmos.com/lama2/
nav:
    - Home: index.md
    - Get Started: 
      - Installation: tutorials/installation.md
      - Examples: tutorials/examples.md
    - Understand:
      - Syntax Guidance: explanation/syntax.md
      - FAQ/RAQ: explanation/faq.md
    - Develop:
      - Architecture: reference/architecture.md
      - IDE/Editor Support: tutorials/editor.md
      - Formal Grammar: reference/grammar.md
      - API Reference: reference/api.md
    - About: 
      - Lama2 History: about/history.md
      - Hexmos: about/hexmos.md
      - Talk to us: about/contact.md
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  features:
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.top 
  logo: logo.png
use_directory_urls: false