site_name: Hexmos Lama2
site_url: https://hexmos.com/lama2
nav:
    - Home: index.md
    - Get Started: 
      - Installation: tutorials/getstarted.md
    - Examples: examples.md
    - Explanation: explanation.md
    - About: about.md
    - API Reference: api.md
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  features:
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.top 
  logo: logo.png
