site_name: Hexmos Lama2
site_url: http://hexmos.com/lama2/
nav:
    - Home: index.md
    - Get Started: 
      - Installation: tutorials/installation.md
      - Examples: tutorials/examples.md
      - Collaboration: tutorials/collaboration.md
    - Understand:
      - Syntax Guidance: explanation/syntax.md
      - The l2 Format: explanation/l2format.md
      - FAQ/RAQ: explanation/faq.md
    - Develop:
      - Design Philosophy: reference/philosophy.md
      - Architecture: reference/architecture.md
      - IDE/Editor Support: tutorials/editor.md
      - Formal Grammar: reference/grammar.md
      - API Reference: reference/api.md
    - About: 
      - Hexmos: about/hexmos.md
      - Talk to us: about/contact.md
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
theme:
  name: material
  features:
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.top 
  logo: logo.png
  favicon: favicon.ico
use_directory_urls: false
repo_url: https://github.com/HexmosTech/Lama2